### ISSUE TITLE
Add support for soft/hard quarantine periods

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#10]
Correct the automation of the cron, for the grace periods and the redemption period.

He's currently changing it to canceled.

**Comment by wmetge** [comment]
hi @coriaweb, we will look into adding the correct mapping for these statuses

**Comment by willdashwood** [comment]
I was about to post a new issue but found this old one. I think that the setting of statuses in the domain sync cron script just needs a little tweaking with it's logic now that WHMCS supports more than previously.

Ideally the OpenProvider API should be improved so that we get more than 1 domain status (DEL) for domains that have expired. I will ask Inna at OP if this could be added to the API. @soberoctober are you just working on the WHMCS module or do you work on the API as well?

Assuming that the OP API can't be improved at this stage to provide more details status information, I think that the domain sync script should first check if "Domain Grace and Redemption Fees" is enabled under General Settings. If it is enabled and the domain status is already set to "Grace" or "Redemption" in WHMCS, do not update unless status in OP changes to something other the DEL (e.g. ACT).

Putting some logic control in there rather than just updating the status to Expired might be the best way of handling it for now.

**Comment by willdashwood** [comment]
Just updating this issue now that I've had a reply from Inna. She tells me that you can already tell if a domain is in grace or redemption depending on if softQuarantineExpiryDate or hardQuarantineExpiryDate is returned when calling searchDomainRequest. Although admittedly it doesn't state that in the documentation:

https://doc.openprovider.eu/API_Module_Domain_searchDomainRequest

I wonder what else is undocumented that might be of use for other issues such as #39 or #32

**Comment by soberoctober** [comment]
@willdashwood @coriaweb 

we're assessing the possibility of tracking these statuses in the module.
i'll post an update once we come up with a working proposal.

**Comment by soberoctober** [comment]
6827882
