### ISSUE TITLE
[BUG] Can't see DOMAIN details

### ISSUE THREAD

**Issue by maverick85** [openprovider/OP-WHMCS7#100]
**Describe the bug**
Whenever WHMCS tries to load the details of any domain, the OpenProvider module prevents the page from rendering and the page stays all white.

**To Reproduce**
1. Go to 'View/Seach Clients' or 'Domain Registrations'
2. Click on any client to open details then go to Domains tab, OR simply select any domain from 'Domain Registrations'
3. The page will come out blank

**Expected behavior**
Domain information/details should come up

**Server info:**
 - WHMCS: 8.0.0
 - Distro: CentOS 8
 - PHP: 7.4.11
 - Web server: httpd

**Comment by MrKoopie** [comment]
@maverick85 Can you [enable debug mode in WHMCS](https://docs.whmcs.com/Enabling_Error_Reporting) and report back the issue you have?

**Comment by maverick85** [comment]
@MrKoopie sorry I should have posted this right away. Not using the debug mode but on the apache log I get the PHP Error as follows:

```
[Thu Oct 01 17:17:47.224078 2020] [proxy_fcgi:error] [pid 1149:tid 139775709226752] [client :56099]
AH01071: Got error 'PHP message: [WHMCS Application] ERROR:
Error: Call to undefined function openprovider_additional_fields() in
/var/www/html/whmcs/resources/domains/dist.additionalfields.php:18
Stack trace: #0 /var/www/html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0): unknown()
#1 /var/www/html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0):
WHMCS\\Domains\\AdditionalFields->fetch()
#2 /var/www/html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0):
WHMCS\\Domains\\AdditionalFields->loadFieldsData()
#3 /var/www/html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0):
WHMCS\\Domains\\AdditionalFields->setTLD()
#4 /var/www/html/whmcs/admin/clientsdomains.php(0):
WHMCS\\Domains\\AdditionalFields->setDomain()
#5 {main} {"exception":"[object] (Error(code: 0):
Call ...', referer: https://whmcs.domain.com/admin/clientsservices.php?userid=13

[Thu Oct 01 17:18:04.762810 2020] [proxy_fcgi:error] [pid 1151:tid 139775876982528] [client :41483]
AH01071: Got error 'PHP message:
PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 8192 bytes) in
/var/www/html/whmcs/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Models/Registrar.php on line 121
PHP message:
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in
/var/www/html/whmcs/vendor/filp/whoops/src/Whoops/Util/Misc.php on line 1
PHP message:
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 65536 bytes) in
Unknown on line 0', referer: https://whmcs.domain.com/admin/clientsservices.php?userid=13
```

**Comment by MrKoopie** [comment]
@maverick85 I'm not sure what causes the high memory usage, but have you tried to increase the limit to 512M? Furthermore, which other modules have you installed? We develop with a memory_limit of 256M and I cannot reproduce these errors.

In regard to the openprovider_additional_fields error: remove this in additionalfields.php. You have not fully removed Openprovider, which is why you are

**Comment by maverick85** [comment]
@MrKoopie since the last update this seems fixed. 

I did not understand your "in regard" comment. Why should I remove additionalfields.php? Is this part of the configuration due and not up to date any more?
Why should I fully remove the Openprovider plugin? Didn't get the sense of this, sorry.

**Comment by wmetge** [comment]
Hi @maverick85 

To clarify the comment regarding "additionalfields.php":
When you installed the Openprovider module, you added a call to the function `openprovider_additional_fields()` in "additionalfields.php"

When you removed the module, you got the error indicating that the function could not be found. In order to get rid of this error, you would either need to reinstall the Openprovider module or remove the call to the `openprovider_additional_fields()` function from the "additionalfields.php" file

Please let us know if there are further issues.

**Comment by maverick85** [comment]
@wmetge I see. It was never my intention to remove the Openprovider module.

What seems to have happened was that the upgrade using WHMCS updater completed successfully, but some bugs were found. Upon looking for a solution, we were advised to download the full-package of whmcs and upload the files.
In the meanwhile, apparently, some folders got totally overwritten, while others simply updated the files.

We then downloaded the full WHMCS-OP plugin and went through the whole process.

Thanks for your feedback. Cheers.
