### ISSUE TITLE
Problems with domain sync

### ISSUE THREAD

**Issue by tmishutin** [openprovider/OP-WHMCS7#3]
We have detected some bug's in domain sync:

1) WhmcsHelpers/DomainSync.php , function get_unprocessed_domains is not using ORDER BY but using limit what can cause a random ordering in MySQL. As a result some of the domains are not being processed.

2) DomainSync.php, function process_domains. Type in catch (line 146)  the word prohibited is spelled wrong.

3) DomainSync.php, function process_domains. Catch exception 'The domain is not in your account; please transfer it to your account first.' , I think this one should be interpreted as "Transferred away".

**Comment by tmishutin** [comment]
4. The sync sends e-mail's with changes, but those changes are not real changes. See the screenshot. This happens with expire & due date, status and autorenew sync.

<img width="199" alt="schermafbeelding 2017-06-21 om 17 13 03" src="https://user-images.githubusercontent.com/11507459/27391761-17d31b56-56a5-11e7-86f4-80836fc39b32.png">

**Comment by wmetge** [comment]
@tmishutin, thank you very much for the feedback.

There is a new release of the module, 2.2.3, which should address points 3 and 4 which you've mentioned.

Regarding  your first point, we plan on addressing this issue in the next release, so that domains will be taken from the list according to a particular order. However, if you set "update interval" to 1 or more, and schedule your cron job to run frequently enough so all domains can be processed within that time frame, then all domains will be processed, just not according to a particular order. 

For example, if you have 1000 domains, and set the processing limit to 200, and set the update interval to 1, then you need to run the domain sync task 5 times every day. Since get_unprocessed_domains only takes domains which haven't been processed within the window specified by the update interval, all domains will be processed even though the select statement takes a random sample of domains from the list.

regarding the spelling of prohibited, this will also be fixed in the next release.
