### ISSUE TITLE
Sync Not Supported by Registrar Module

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#34]
We are receiving messages from the WHMCS update with the list of domains and the following message:

Sync Not Supported by Registrar Module

Any way to fix it?

**Comment by soberoctober** [comment]
Hi @coriaweb 
Does this list include all of your domains or just a part?

**Comment by theemstra** [comment]
Hi,

Can confirm. This issue started for us after upgrading WHMCS to the latest version.
It includes all domains.
DomainSync.php is ran.

The email is coming from WHMCS, not the openprovider module itself, because the sync is now initiated from whmcs, if supported by the domain provider.

**Comment by willdashwood** [comment]
This issue has been around for over a year. The OpenProvider module doesn't use WHMCS cron. That's why you have to set up a separate cron for modules/registrars/openprovider/cron/DomainSync.php

I asked OpenProvider support team about it November 2017. Here's their reply:

> The choice to use a separate cron script was made because of a number of limitations on the part of the WHMCS cron. The main issue is that the WHMCS sync method doesn't allow for domain autorenew, and whois privacy protection statuses to be synchronized, which is something many of our customers needed.

At the time I didn't really question it but having wrote a few of my own WHMCS modules since then, I'm not sure why synchronising the other data can't be done via a separate cron hook.

I also asked if they could at least suppress the "Sync Not Supported by Registrar Module" warnings that clog up the messages as it makes it harder to spot genuine sync errors. I was told "I've opened a ticket to investigate whether this is possible.". Like I say, that was November 2017.

**Comment by theemstra** [comment]
> This issue has been around for over a year. The OpenProvider module doesn't use WHMCS cron. That's why you have to set up a separate cron for modules/registrars/openprovider/cron/DomainSync.php

Also when the cron is set up, the message will appear, because it's not possible to switch the domain module sync off in WHMCS settings, at least afaik.

> I also asked if they could at least suppress the "Sync Not Supported by Registrar Module" warnings that clog up the messages as it makes it harder to spot genuine sync errors. I was told "I've opened a ticket to investigate whether this is possible.". Like I say, that was November 2017.

That is sad to hear, let's keep this issue open until it is resolved in this module.

**Comment by willdashwood** [comment]
I think I should have posted it on here rather than via OpenProvider as perhaps it's been forgotten about. Or maybe not deemed important enough to fix.

**Comment by soberoctober** [comment]
We are aware of recent frequency spikes of the issue and are currently exploring possible solutions to mitigate it.

**Comment by willdashwood** [comment]
@soberoctober Thanks. It's not a recent issue, as I say above it's been this way since at least November 2017. But I guess what you mean is that more people are using the latest release of this module now and raising the issue. As I say, I should have posted it on here rather than via a support ticket.

IMO, everything that can be done via the "proper" WHMCS cron, should be. And anything that can't (i.e. domain autorenew and whois privacy protection statuses) can be done on a separate cron.

**Comment by solucionesuno** [comment]
i have the some problem here!

**Comment by solucionesuno** [comment]
Hello, no news about this bug?

**Comment by soberoctober** [comment]
fixed in [v3.0](https://github.com/openprovider/OP-WHMCS7/tree/v3.0)
