### ISSUE TITLE
DNSSEC management?

### ISSUE THREAD

**Issue by tamerciaga** [openprovider/OP-WHMCS7#37]
Will this be implemented? It's becoming a core feature of domain management.

**Comment by soberoctober** [comment]
Hi @tamerciaga 

Since one cannot manage the zone directly from the module, we don't see much sense in adding just a DNSSEC toggle. 
That being said, we're researching on integrating our registrar module with Openprovider Single DNS panel that is currently in beta. That will allow for direct zone management from Client area, including DNSSEC.
