### ISSUE TITLE
Address 'Little Mollington Hall ' could not be splitted into street name and house number. 

### ISSUE THREAD

**Issue by willdashwood** [openprovider/OP-WHMCS7#47]
When trying to register a .tv domain we received the following error complaining about the information in the "Address 1" field.

Address 'Little Mollington Hall ' could not be splitted into street name and house number. 

Not all addresses have a house number in the UK. I was able to register the domain manually fine with the correct address.

**Comment by soberoctober** [comment]
Hi @willdashwood 

We added a library that parses address fields and extracts just those two main entities: street name and house number. We believe that it might prevent problems with prohibited characters in certain address fields(e.g. address suffix field).

We'll improve the extraction to take into account a notation that lacks house numbers.

**Comment by soberoctober** [comment]
Hi @willdashwood 

Strictly speaking, number field is considered to be mandatory, both in our [documentation](https://doc.openprovider.eu/API_Format_Address) and in RCP.
In reality, as it turns out, our API is far more forgiving when it comes to customer data.

We are going to review this from both sides and adjust the parser library accordingly.

**Comment by willdashwood** [comment]
Since a lot of properties in the UK do not have a number, just a name, this does need to be addressed. Thanks

**Comment by thomashoeky** [comment]
Some turkish addresses dont have numbers either, I had to add "0" to a customer to get the domains to register properly

**Comment by soberoctober** [comment]
fixed in [v3.0](https://github.com/openprovider/OP-WHMCS7/tree/v3.0)
