### ISSUE TITLE
[FR] Add support for DNSSEC management

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#58]
In CPanel version 84, you already have the option to create DNSSEC.

Would it be possible to manage this with Openprovider from WHMCS so that customers can activate it?

Greetings!

**Comment by soberoctober** [comment]
@coriaweb if I understand correctly you'd want to see an ability to add and manage DS records for domains that are pointed to 3rd party DNS via the module?

Is that correct?

**Comment by coriaweb** [comment]
Yes, it would be interesting for the client to see in the control panel "cpanel" the DNSSEC records and to be able to enter the client area in WHMCS and put it for his domain.

Greetings!

**Comment by MrKoopie** [comment]
Before it gets implemented, I prefer to have a GUI for DNSSEC. The next step would be to create module-specific integrations for panels such as cPanel, Plesk and DirectAdmin.

@soberoctober @wmetge What do you think?

**Comment by albertodominguez15** [comment]
@MrKoopie A GUI would definitively a good idea. This would allow customers at least to manage DNSSEC themselves.

Also, in my case it would be very helpful if DNSSEC was de-activated per default anytime a customer changes the DNS to anything but the default DNS (ns1.openprovider.nl, etc.).  

Currently, I'm getting 2-3 inquiries a day on average from customers  requesting the deactivation of DNSSEC parameter.

This is the scenario:

1) A costumer registers a domain name using the default DNS (ns1.openprovider.nl...)
2) Once the domain is registered, the customer changes the DNS to anything else (i.e. cloudflare).
3) Since DNSSEC is still active, the new DNS information doesn't become fully active and the domain doesn't respond to the new server. 

This is when I get the inquiry from the customer and I have to log into Opensprovider's admin panel to then manually de-activate DNSSEC. 

Therefore, for me it would be a big time saver if the module could already de-activate the DNSSEC protocols for me instead of having to do it manually all the time.

**Comment by RoelReijn** [comment]
Would love to see this as well!

**Comment by wmetge** [comment]
Hello @RoelReijn @coriaweb @albertodominguez15 ,
thank you for your feedback. We are going to roll out these features within the next release. Initially, customers will be able to switch on/off DNSSEC, as well as adding, modifying, and deleting keys. 

support for 3rd parties will be in a subsequent release

**Comment by coriaweb** [comment]
> Hello @RoelReijn @coriaweb @albertodominguez15 ,
> thank you for your feedback. We are going to roll out these features within the next release. Initially, customers will be able to switch on/off DNSSEC, as well as adding, modifying, and deleting keys.
> 
> support for 3rd parties will be in a subsequent release

Hello!

We really don't need this anymore, well yes, we do, but not for CPanel, we are stopping working with CPanel, we have more than 90% of the clients migrated to CWP: https://control-webpanel.com/

**Comment by wmetge** [comment]
@coriaweb please see the latest release for this functionality: https://github.com/openprovider/OP-WHMCS7#allow-end-users-to-edit-dnssec-records
