### ISSUE TITLE
[BUG] Registrar Lock editable at domains who doesn't support it

### ISSUE THREAD

**Issue by DAThosting** [openprovider/OP-WHMCS7#94]
**Describe the bug**
Some domains e.g. .de doesn't support a registrar lock.
At those domains all customers get a warning message on their clientarea.
It isn't possible to set the registrar lock, cause it isn't supported.

**To Reproduce**
1. Login as user'
2. Switch to domains
3. Select a domain

**Expected behavior**
Hide error and sidebar link.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/16845703/90778359-cf8d4780-e2fc-11ea-861d-0ca0c8174666.png)

**Comment by wmetge** [comment]
Hi @DAThosting, thanks for taking the time to report this bug to our github page. 

Unfortunately, hiding the sidebar and the error message as you have described are outside the scope of a registrar module, and can only be changed in the WHMCS core code. 

I would direct your attention to this request page which describes this issue to the WHMCS developers: https://requests.whmcs.com/topic/option-for-registrar-lock 

We have had quite a few users complain, so it's surprising that this issue has received so little attention from their side. 

As a workaround, you can remove the registrar lock option for all Openprovider domains by commenting out the functions `"openprovider_GetRegistrarLock"` and `"openprovider_SaveRegistrarLock"` in the file:
`whmcs/modules/registrars/openprovider/openprovider.php`

This will make it appear to WHMCS that the module does not support domain locking in general, and the warning will not be displayed for any domain. Since domains are automatically created with locked status, this might be an appropriate option for you. However, you will need to manually intervene in the case that your customers wants to unlock their domain for transfer.
