### ISSUE TITLE
[BUG] Registrar TLD Sync appears blank

### ISSUE THREAD

**Issue by maverick85** [openprovider/OP-WHMCS7#98]
**Describe the bug**
On WHMCS 8.0.0 the Registrar TLD Sync module does not work.

**To Reproduce**
1. Go to 'Utilities > Registrar TLD Sync'
2. Click on 'OpenProvider'
3. Wait for the module to load domain pricing info
4. error is that nothing happens

**Expected behavior**
A list with the TLD and prices etc should appear

**Server info:**
 - WHMCS version: 8.0.0
 - Distro: CentOS 8
 - PHP: 7.4.11
 - Web server: httpd

**Additional context**
I updated my whmcs installation to 8.0.0, stopped working

**Comment by markschrik** [comment]
We are currently experiencing the same. We'd love to use it. Any clue on expecting to support WHMCS 8?

**Comment by wmetge** [comment]
@maverick85 and @markschrik, thank you for letting us know about this issue you’re experiencing, we’re investigating it and hope to have a solution before the end of next week (September 9th)

**Comment by maverick85** [comment]
Hi @wmetge thank you for your feedback. Please let us know if you need anything else.

**Comment by wmetge** [comment]
@maverick85 

It seems that this issue was being caused by WHMCS 8.0, and has been solved in 8.0.1

Please let us know if upgrading to the latest version of WHMCS does not solve the issue.

Note that the [latest release](https://github.com/openprovider/OP-WHMCS7/releases/tag/3.3.2) of the Openprovider module uses a cron job to sync all TLDs, and the [usage is described here](https://github.com/openprovider/OP-WHMCS7/blob/master/docs/TLD_Pricing_sync_Utility.md)

The cron job is used because it ensures that servers with lower timeout values can process the >1500 TLDs which Openprovider offers.

**Comment by maverick85** [comment]
Hi @wmetge , thank you for your feedback.
Upon updating to 8.0.1 I see no changes. I am going to review the latest release and see the documentation, will come back to give feedback. cheers

**Comment by maverick85** [comment]
Hi @wmetge 

So I uploaded the latest release and went through the documentation.
I have a question about TLD Pricing Sync, I see there are two options, SSH and Cron, being that cron would be supposedly to whom lacks SSH access, is that it?

I would like to know why to disable the Cron, instead of leaving it to run once or twice a month?
Also, how often are the prices updated? And are they updated based on a given calendar, to launch new prices for each month?
If so then I'd only need to run the cron once per month, no?

Can you please give me your thoughts on this? thank you.

**Comment by wmetge** [comment]
Hi @maverick85 ,

> ... cron would be supposedly to whom lacks SSH access, is that it?
yes, we included it as an example for those who may not have SSH access

> why to disable the Cron, instead of leaving it to run once or twice a month?
We've described it in this way for those users who use the cron option rather than running it by CLI, and to encourage them to not use unnecessary server resource. 

There is certainly no problem in running it regularly, but please note that the price changes are only cached by this script, in order to import them into WHMCS, you will need to use TLD sync utility from the admin area of your WHMCS.

>Also, how often are the prices updated? And are they updated based on a given calendar, to launch new prices for each month?
Since we sell at cost price to members, we offer promotions and make price changes based on our suppliers' price changes, so we generally don't have a set schedule for changes, we can only inform our customers as soon as our suppliers inform us. Price increases for domains are fairly rare, generally only when a registry is acquired by new investors. Much more common are temporary promotional prices, which again are dictated by our suppliers. You can find a calendar of price promotions in the Openprovider newsletter or on the website: https://openprovider.com/membership-plans/promotions/ 

>Another note: here: https://github.com/openprovider/OP-WHMCS7 on Step 9 the configure cron link goes to a private gitlab install, so this link/instruction isn't accessible.

thanks for pointing this out, we'll update it ASAP.

**Comment by maverick85** [comment]
@wmetge 

Hi there, I'm coming back regarding some questions about the configuration steps.
First, the Step 9 apparently still hasn't been corrected and is still directing to an inaccessible destination.

Also, on [Install the DNS Management Options](https://github.com/openprovider/OP-WHMCS7#install-the-dns-management-options) there's this:

> Step 3: Update the MX priority field with `or $dnsrecord.type eq "SRV"` in the 'if/else' block.
>
> This 'if' statement is used twice in the file. Replace both.
>
> `{if $dnsrecord.type eq "MX"}`
> `{if $dnsrecord.type eq "MX" or $dnsrecord.type eq "SRV"}`

But I can only find this statement once on the updated six template.
Cheers
